// Lead Proposal Service — localStorage CRUD for proposals linked to leads

import type { ProposalSection } from './proposalGeneratorService';

// ===== Types =====

export interface StoredProposal {
  id: string;
  leadId: string;
  version: number;
  status: 'draft' | 'sent' | 'viewed' | 'accepted' | 'rejected';
  generatedAt: string;
  sentAt?: string;
  viewedAt?: string;
  language: 'en' | 'es';
  coverTitle: string;
  coverSubtitle: string;
  sections: ProposalSection[];
  clientName: string;
  systemKwp: number;
  totalInvestment: number;
  annualSavings: number;
  paybackYears: number;
  annualCO2Tons: number;
  panelCount: number;
}

export interface ProposalStats {
  total: number;
  draft: number;
  sent: number;
  accepted: number;
  rejected: number;
  conversionRate: number;
}

// ===== Constants =====

const STORAGE_KEY = 'solaris-proposals';

// ===== Internal helpers =====

function readAll(): StoredProposal[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

function writeAll(proposals: StoredProposal[]): void {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(proposals));
}

// ===== CRUD =====

export function saveProposal(proposal: StoredProposal): void {
  const all = readAll();
  const idx = all.findIndex((p) => p.id === proposal.id);
  if (idx >= 0) {
    all[idx] = proposal;
  } else {
    all.push(proposal);
  }
  writeAll(all);
}

export function getProposalsForLead(leadId: string): StoredProposal[] {
  return readAll()
    .filter((p) => p.leadId === leadId)
    .sort((a, b) => new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime());
}

export function getProposal(proposalId: string): StoredProposal | null {
  return readAll().find((p) => p.id === proposalId) ?? null;
}

export function updateProposalStatus(
  id: string,
  status: StoredProposal['status'],
  sentAt?: string
): void {
  const all = readAll();
  const idx = all.findIndex((p) => p.id === id);
  if (idx < 0) return;
  all[idx] = { ...all[idx], status, ...(sentAt ? { sentAt } : {}) };
  writeAll(all);
}

export function deleteProposal(id: string): void {
  writeAll(readAll().filter((p) => p.id !== id));
}

export function getAllProposals(): StoredProposal[] {
  return readAll().sort(
    (a, b) => new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime()
  );
}

export function getProposalStats(): ProposalStats {
  const all = readAll();
  const draft = all.filter((p) => p.status === 'draft').length;
  const sent = all.filter((p) => p.status === 'sent' || p.status === 'viewed').length;
  const accepted = all.filter((p) => p.status === 'accepted').length;
  const rejected = all.filter((p) => p.status === 'rejected').length;
  const decided = accepted + rejected;
  return {
    total: all.length,
    draft,
    sent,
    accepted,
    rejected,
    conversionRate: decided > 0 ? Math.round((accepted / decided) * 100) : 0,
  };
}

// ===== WhatsApp Share =====

export function buildProposalWhatsAppMessage(proposal: StoredProposal): string {
  const isEs = proposal.language === 'es';
  const fmtCurrency = (n: number) => `$${n.toLocaleString('en-US')}`;
  const roi = proposal.totalInvestment > 0
    ? ((proposal.annualSavings * 25 / proposal.totalInvestment - 1) * 100).toFixed(0)
    : '0';

  if (isEs) {
    return `🌞 *Propuesta Solar — ${proposal.clientName}*

⚡ Sistema: ${proposal.systemKwp} kWp (${proposal.panelCount || '—'} paneles)
💰 Inversión: ${fmtCurrency(proposal.totalInvestment)}
💵 Ahorro anual: ${fmtCurrency(proposal.annualSavings)}
📅 Recuperación: ${proposal.paybackYears.toFixed(1)} años
🌱 CO₂: ${(proposal.annualCO2Tons || 0).toFixed(1)} tons/año reducción

📊 ROI 25 años: ${roi}%

_Generado por Solaris Panama_`;
  }

  return `🌞 *Solar Proposal — ${proposal.clientName}*

⚡ System: ${proposal.systemKwp} kWp (${proposal.panelCount || '—'} panels)
💰 Investment: ${fmtCurrency(proposal.totalInvestment)}
💵 Annual Savings: ${fmtCurrency(proposal.annualSavings)}
📅 Payback: ${proposal.paybackYears.toFixed(1)} years
🌱 CO₂: ${(proposal.annualCO2Tons || 0).toFixed(1)} tons/year reduction

📊 25-Year ROI: ${roi}%

_Generated by Solaris Panama_`;
}

export function getProposalWhatsAppUrl(proposal: StoredProposal, phone?: string): string {
  const message = encodeURIComponent(buildProposalWhatsAppMessage(proposal));
  if (phone) {
    const cleanPhone = phone.replace(/[^\d+]/g, '').replace(/^\+/, '');
    return `https://wa.me/${cleanPhone}?text=${message}`;
  }
  return `https://wa.me/?text=${message}`;
}
